name: Firebase Cleanup Old Runs

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install firebase-admin

    - name: Write service account key to file
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > serviceAccountKey.json

    - name: Run cleanup script
      run: python cleanup.py
